# Generated by Django 5.1.1 on 2024-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_alert',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
