# Generated by Django 5.1.1 on 2024-10-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_mail_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_alert',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
