# Generated by Django 5.1.1 on 2024-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='gas_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
