# Generated by Django 5.1.1 on 2024-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sensordata_last_alert_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='last_alert_sent',
        ),
        migrations.AddField(
            model_name='user',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
