# Generated by Django 4.2.16 on 2024-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_imageprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='freshness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
